CREATE TABLE foodie
(
slno INT PRIMARY KEY IDENTITY(1, 1),
food_name VARCHAR(25),
category VARCHAR(20),
cuisine VARCHAR(25),
taste VARCHAR(20),
price INT,
rating DECIMAL,
best_place VARCHAR(25)
);
INSERT INTO foodie
VALUES ('Biryani', 'MainCourse', 'Indian', 'Rich', 200, 4.9, 'Hyderabad'),
('ButterChicken', 'MainCourse', 'Indian', 'Creamy', 350, 4.8, 'Delhi'),
('MasalaDosa', 'Breakfast', 'Indian', 'Crispy', 120, 4.8, 'Bengaluru'),
('PaniPuri', 'StreetFood', 'Indian', 'Tangy', 50, 4.7, 'Mumbai'),
('RoganJosh', 'MainCourse', 'Indian', 'Spicy', 400, 4.6, 'Kashmir'),
('CholeBhature', 'Breakfast', 'Indian', 'Savory', 150, 4.8, 'Punjab'),
('Idli', 'Breakfast', 'Indian', 'Soft', 60, 4.5, 'Chennai'),
('VadaPav', 'StreetFood', 'Indian', 'Spicy', 40, 4.7, 'Mumbai'),
('PaneerTikka', 'Appetizer', 'Indian', 'Smoky', 220, 4.6, 'Amritsar'),
('DalMakhani', 'MainCourse', 'Indian', 'Buttery', 180, 4.8, 'Delhi'),
('PavBhaji', 'StreetFood', 'Indian', 'Buttery', 140, 4.7, 'Mumbai'),
('Samosa', 'Snack', 'Indian', 'Crispy', 30, 4.6, 'Delhi'),
('Rasgulla', 'Dessert', 'Indian', 'Sweet', 90, 4.7, 'Kolkata'),
('GulabJamun', 'Dessert', 'Indian', 'Sugary', 80, 4.8, 'Lucknow'),
('Jalebi', 'Dessert', 'Indian', 'Syrupy', 70, 4.7, 'Jaipur'),
('RajmaChawal', 'MainCourse', 'Indian', 'Comforting', 160, 4.6, 'Chandigarh'),
('Poha', 'Breakfast', 'Indian', 'Light', 70, 4.5, 'Indore'),
('Upma', 'Breakfast', 'Indian', 'Mild', 60, 4.3, 'Chennai'),
('FishCurry', 'Seafood', 'Indian', 'Spicy', 320, 4.7, 'Goa'),
('TandooriChicken', 'Grill', 'Indian', 'Smoky', 380, 4.8, 'Punjab'),
('KathiRoll', 'StreetFood', 'Indian', 'Savory', 120, 4.6, 'Kolkata'),
('MisalPav', 'StreetFood', 'Indian', 'Fiery', 110, 4.7, 'Pune'),
('Dhokla', 'Snack', 'Indian', 'Soft', 80, 4.5, 'Ahmedabad'),
('LittiChokha', 'MainCourse', 'Indian', 'Smoky', 130, 4.6, 'Patna'),
('SarsonSaag', 'MainCourse', 'Indian', 'Earthy', 190, 4.7, 'Punjab'),
('MakkiRoti', 'Bread', 'Indian', 'Rustic', 50, 4.5, 'Ludhiana'),
('HyderabadiHaleem', 'MainCourse', 'Indian', 'Rich', 250, 4.9, 'Hyderabad'),
('Appam', 'Breakfast', 'Indian', 'Soft', 90, 4.4, 'Kochi'),
('MalaiKofta', 'MainCourse', 'Indian', 'Creamy', 240, 4.7, 'Agra'),
('BhindiMasala', 'MainCourse', 'Indian', 'Spicy', 150, 4.3, 'Jaipur'),
('PalakPaneer', 'MainCourse', 'Indian', 'Mild', 210, 4.6, 'Delhi'),
('Chaat', 'StreetFood', 'Indian', 'Tangy', 60, 4.8, 'Lucknow'),
('Korma', 'MainCourse', 'Indian', 'Rich', 300, 4.5, 'Hyderabad'),
('AlooParatha', 'Breakfast', 'Indian', 'Buttery', 100, 4.8, 'Punjab'),
('MeduVada', 'Snack', 'Indian', 'Crispy', 70, 4.5, 'Chennai'),
('Kheer', 'Dessert', 'Indian', 'Creamy', 90, 4.4, 'Varanasi'),
('Kulfi', 'Dessert', 'Indian', 'Chilled', 60, 4.7, 'Delhi'),
('MysorePak', 'Dessert', 'Indian', 'Rich', 120, 4.6, 'Mysuru'),
('Shrikhand', 'Dessert', 'Indian', 'Sweet', 110, 4.5, 'Gujarat'),
('Pesarattu', 'Breakfast', 'Indian', 'Savory', 80, 4.4, 'Vijayawada'),
('Chicken65', 'Appetizer', 'Indian', 'Fiery', 260, 4.8, 'Chennai'),
('ChettinadChicken', 'MainCourse', 'Indian', 'Spicy', 340, 4.7, 'Madurai'),
('Nihari', 'MainCourse', 'Indian', 'Rich', 360, 4.6, 'Lucknow'),
('BainganBharta', 'MainCourse', 'Indian', 'Smoky', 170, 4.3, 'Haryana'),
('DumAloo', 'MainCourse', 'Indian', 'Spicy', 180, 4.4, 'Kashmir'),
('Rasmalai', 'Dessert', 'Indian', 'Creamy', 100, 4.8, 'Kolkata'),
('Thepla', 'Bread', 'Indian', 'Spicy', 50, 4.5, 'Surat'),
('Undhiyu', 'MainCourse', 'Indian', 'Mixed', 220, 4.4, 'Gujarat'),
('Pongal', 'Breakfast', 'Indian', 'Comforting', 90, 4.5, 'TamilNadu'),
('Murukku', 'Snack', 'Indian', 'Crunchy', 40, 4.4, 'Madurai'),
('Pizza', 'FastFood', 'Italian', 'Cheesy', 450, 4.7, 'Naples'),
('Sushi', 'Seafood', 'Japanese', 'Mild', 700, 4.8, 'Tokyo'),
('Burger', 'FastFood', 'American', 'Savory', 250, 4.4, 'NewYork'),
('Tacos', 'StreetFood', 'Mexican', 'Spicy', 180, 4.5, 'MexicoCity'),
('Croissant', 'Bakery', 'French', 'Buttery', 120, 4.7, 'Paris'),
('Paella', 'MainCourse', 'Spanish', 'Savory', 550, 4.6, 'Valencia'),
('Ramen', 'Soup', 'Japanese', 'Umami', 400, 4.8, 'Osaka'),
('Shawarma', 'FastFood', 'MiddleEastern', 'Smoky', 180, 4.6, 'Dubai'),
('Pho', 'Soup', 'Vietnamese', 'Aromatic', 300, 4.7, 'Hanoi'),
('Lasagna', 'MainCourse', 'Italian', 'Cheesy', 480, 4.8, 'Milan'),
('Kimchi', 'SideDish', 'Korean', 'Tangy', 90, 4.5, 'Seoul'),
('Falafel', 'StreetFood', 'MiddleEastern', 'Crispy', 150, 4.4, 'Beirut'),
('DimSum', 'Appetizer', 'Chinese', 'Light', 350, 4.7, 'HongKong'),
('Gelato', 'Dessert', 'Italian', 'Creamy', 140, 4.9, 'Florence'),
('PadThai', 'Noodles', 'Thai', 'Tangy', 320, 4.7, 'Bangkok'),
('PekingDuck', 'MainCourse', 'Chinese', 'Crispy', 900, 4.9, 'Beijing'),
('Bibimbap', 'MainCourse', 'Korean', 'Savory', 380, 4.6, 'Busan'),
('Burrito', 'FastFood', 'Mexican', 'Filling', 260, 4.5, 'SanDiego'),
('Baklava', 'Dessert', 'Turkish', 'Nutty', 160, 4.7, 'Istanbul'),
('Waffles', 'Breakfast', 'Belgian', 'Sweet', 170, 4.6, 'Brussels'),
('Hotdog', 'FastFood', 'American', 'Smoky', 130, 4.2, 'Texas'),
('Tempura', 'Seafood', 'Japanese', 'Crispy', 520, 4.7, 'Kyoto'),
('Gnocchi', 'MainCourse', 'Italian', 'Soft', 410, 4.5, 'Turin'),
('Enchilada', 'MainCourse', 'Mexican', 'Spicy', 340, 4.4, 'Guadalajara'),
('Tiramisu', 'Dessert', 'Italian', 'Creamy', 220, 4.9, 'Sicily'),
('Fajitas', 'MainCourse', 'Mexican', 'Smoky', 360, 4.5, 'Monterrey'),
('Udon', 'Noodles', 'Japanese', 'Savory', 300, 4.6, 'Nagoya'),
('Hummus', 'Dip', 'MiddleEastern', 'Smooth', 140, 4.4, 'Jerusalem'),
('Macarons', 'Dessert', 'French', 'Sweet', 250, 4.8, 'Lyon'),
('Meatballs', 'MainCourse', 'Swedish', 'Juicy', 390, 4.5, 'Stockholm'),
('Pierogi', 'Snack', 'Polish', 'Savory', 220, 4.3, 'Warsaw'),
('Ceviche', 'Seafood', 'Peruvian', 'Citrusy', 450, 4.6, 'Lima'),
('Omelette', 'Breakfast', 'French', 'Fluffy', 100, 4.2, 'Nice'),
('Pretzel', 'Snack', 'German', 'Salty', 90, 4.4, 'Munich'),
('Cheesecake', 'Dessert', 'American', 'Creamy', 240, 4.8, 'NewYork'),
('Moussaka', 'MainCourse', 'Greek', 'Rich', 430, 4.5, 'Athens'),
('Schnitzel', 'MainCourse', 'German', 'Crispy', 500, 4.6, 'Berlin'),
('Tteokbokki', 'StreetFood', 'Korean', 'Spicy', 210, 4.7, 'Incheon'),
('Quiche', 'Bakery', 'French', 'Savory', 260, 4.3, 'Bordeaux'),
('LobsterRoll', 'Seafood', 'American', 'Buttery', 850, 4.9, 'Maine'),
('Ravioli', 'Pasta', 'Italian', 'Cheesy', 420, 4.5, 'Genoa'),
('Focaccia', 'Bakery', 'Italian', 'Herby', 160, 4.4, 'Bari'),
('Carbonara', 'Pasta', 'Italian', 'Creamy', 470, 4.8, 'Rome'),
('Yakitori', 'Grill', 'Japanese', 'Smoky', 280, 4.6, 'Sapporo'),
('SpringRolls', 'Appetizer', 'Chinese', 'Crunchy', 140, 4.4, 'Shanghai'),
('FishChips', 'FastFood', 'British', 'Crispy', 300, 4.3, 'Liverpool'),
('Cannoli', 'Dessert', 'Italian', 'Sweet', 180, 4.7, 'Palermo'),
('Bruschetta', 'Appetizer', 'Italian', 'Fresh', 160, 4.5, 'Verona'),
('Baguette', 'Bakery', 'French', 'Crispy', 100, 4.6, 'Marseille'),
('Couscous', 'MainCourse', 'Moroccan', 'Mild', 350, 4.4, 'Marrakech'),
('Jambalaya', 'MainCourse', 'American', 'Spicy', 410, 4.5, 'Louisiana'),
('Laksa', 'Soup', 'Malaysian', 'Spicy', 330, 4.8, 'KualaLumpur'),
('Okonomiyaki', 'StreetFood', 'Japanese', 'Umami', 370, 4.7, 'Hiroshima');
SELECT * FROM foodie;
